import TheFooter from '@/components/TheFooter'
import TheHeader from '@/components/TheHeader'
import type { Metadata } from 'next'
import { Roboto_Flex } from 'next/font/google'

const roboto = Roboto_Flex({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html style={{margin: '0 auto'}} lang="en">
        <body className={roboto.className}>
          <TheHeader />
            {children}
          <TheFooter />
        </body>
    </html>
  )
}
